### ISSUE TITLE
`ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by Belissimo-T** [seekers-dev/seekers-java#30]
```
SCHWERWIEGEND: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3acc08ba
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.base/java.util.HashMap.keysToArray(HashMap.java:958)
	at java.base/java.util.HashSet.toArray(HashSet.java:381)
	at com.karlz.exchange.Mapper.eachTo(Mapper.java:80)
	at com.karlz.exchange.Corresponding.transform(Corresponding.java:19)
	at com.seekers.grpc.SeekersDispatchHelper.associated(SeekersDispatchHelper.java:38)
	at com.seekers.grpc.SeekersServer$SeekersService.status(SeekersServer.java:109)
	at com.seekers.grpc.game.SeekersGrpc$MethodHandlers.invoke(SeekersGrpc.java:347)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
```

**Comment by karl-zschiebsch** [comment]
Fixed with new library.
